from UniversalBot.kik_bot import KIK
from UniversalBot.microsoft_bot import MicrosoftBot
from UniversalBot.telegram_bot import Telegram
from UniversalBot.telegram_bot_strangergeo import StrangerGeoTelegram
from UniversalBot.facebook_bot import FacebookBot
